Nijmi Bajracharya ID:2508912 Group:L5CG11

In [23]:
#problem:1
#q1
import numpy as np
arr = np.empty((2,2))
print(arr)

[[4.4e-323 5.4e-323]
 [4.9e-323 5.9e-323]]


In [3]:
#q2
arr = np.ones((4,2))
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [4]:
#q3
arr = np.full((4,2), 13)
print(arr)

[[13 13]
 [13 13]
 [13 13]
 [13 13]]


In [5]:
#q4
arr = [[1,2], [3,4]]
arr2 = np.zeros_like(arr)
print(arr2)

[[0 0]
 [0 0]]


In [6]:
#q4
arr = [[1,2], [3,4]]
arr2 = np.ones_like(arr)
print(arr2)

[[1 1]
 [1 1]]


In [7]:
#q5
new_list = [1,2,3,4]
arr = np.array(new_list)
print(arr)

[1 2 3 4]


In [12]:
#problem:2
#q1
arr = np.arange(10, 50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [13]:
#q2
arr=np.arange(0,9)
reshape_arr=arr.reshape(3,3)
print(reshape_arr)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [14]:
#q3
arr= np.eye(3)
print(arr)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
#q4
import random as random
arr = np.random.random(30)
print(arr)
mean= np.mean(arr)
print(f"mean is {mean}")

[0.58457631 0.55591929 0.81547807 0.85668872 0.76220516 0.65729947
 0.14907315 0.9186648  0.82924441 0.46624155 0.15050017 0.63027301
 0.66877499 0.68251816 0.85535749 0.32410206 0.59278897 0.0194208
 0.89794085 0.28819047 0.27340379 0.95093872 0.84448173 0.47239292
 0.88210385 0.11424719 0.65418203 0.55318663 0.77788668 0.63430638]
mean is 0.5954129271543986


In [17]:
#q5
arr= np.random.random((10,10))
max= np.max(arr)
min=np.min(arr)
print(f"max is {max} and min is {min}")

max is 0.9601763332489337 and min is 0.0072586610394230755


In [18]:
#q6
arr=np.zeros(10)
print(arr)
arr[4]=1
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [19]:
#q7
arr=[1, 2, 0, 0, 4, 0]
reverse = np.flip(arr)
print(reverse)

[0 4 0 0 2 1]


In [20]:
#q8
n,m = 5, 5
arr = np.zeros((n,m))
arr[0, :] = 1
arr[-1, :] = 1
arr[:, 0] = 1
arr[:, -1] = 1
print(arr)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [21]:
#q9
checkboard=np.ones((8,8))
checkboard[1::2, ::2]=0
checkboard[::2, 1::2]=0
print(checkboard)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [24]:
#problem:3
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
print(np.add(x,y))
print(np.add(v,w))
print(np.subtract(x,y))
print(np.subtract(v,w))
print((x,y)*2)
print((v,w)*5)
print(np.square(x))
print(np.square(y))
print(np.square(v))
print(np.square(w))
print(np.dot(v,w))
print(np.dot(x,v))
print(np.dot(x,y))
print(np.concatenate((x,y), axis=0))#
v=v.reshape(2,1)
w=w.reshape(2,1)
print(np.concatenate((v,w), axis=1))
print(np.concatenate((x,v), axis =1))

[[ 6  8]
 [10 13]]
[20 22]
[[-4 -4]
 [-4 -3]]
[-2 -2]
(array([[1, 2],
       [3, 5]]), array([[5, 6],
       [7, 8]]), array([[1, 2],
       [3, 5]]), array([[5, 6],
       [7, 8]]))
(array([ 9, 10]), array([11, 12]), array([ 9, 10]), array([11, 12]), array([ 9, 10]), array([11, 12]), array([ 9, 10]), array([11, 12]), array([ 9, 10]), array([11, 12]))
[[ 1  4]
 [ 9 25]]
[[25 36]
 [49 64]]
[ 81 100]
[121 144]
219
[29 77]
[[19 22]
 [50 58]]
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 11]
 [10 12]]
[[ 1  2  9]
 [ 3  5 10]]


In [26]:
#problem:4
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
A_inverse=np.linalg.inv(A)
print(np.dot(A, A_inverse))
print(np.dot(A,B))
print(np.dot(B,A))
AB = np.dot(A,B)
at= np.transpose(A)
bt= np.transpose(B)
print(np.dot(at,bt))

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
[[23 13]
 [51 29]]
[[36 44]
 [13 16]]
[[36 13]
 [44 16]]


In [27]:
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])
A_inverse = np.linalg.inv(A)
X = np.dot(A_inverse, B)
print(X)

[ 2.  1. -2.]


In [37]:
#experiment
import timeit
list1 = list(range(1000000))
list2 = list(range(1000000))


In [36]:
#q1
from timeit import timeit
def add_python(Z1, Z2):
  return [z1 + z2 for z1, z2 in zip(Z1, Z2)]
def add_numpy(Z1, Z2):
  return np.add(Z1, Z2)
Z1 = random.sample(range(1000000), 10000)
Z2 = random.sample(range(1000000), 10000)
python_time = timeit("add_python(Z1,Z2)", globals=globals(), number=100)
numpy_time = timeit("add_numpy(Z1,Z2)", globals=globals(), number=100)
print(f"Pure Python addition: {python_time:.2f} s per loop")
print(f"Numpy addition: {numpy_time:.2f} s per loop")

Pure Python addition: 0.06 s per loop
Numpy addition: 0.12 s per loop


In [35]:
#q2
from timeit import timeit
def mul_python(Z1, Z2):
  return [z1 * z2 for z1, z2 in zip(Z1, Z2)]
def mul_numpy(Z1, Z2):
  return np.multiply(Z1, Z2)
Z1 = random.sample(range(1000000), 10000)
Z2 = random.sample(range(1000000), 10000)
python_time = timeit("mul_python(Z1,Z2)", globals=globals(), number=100)
numpy_time = timeit("mul_numpy(Z1,Z2)", globals=globals(), number=100)
print(f"Pure Python multiplication: {python_time:.2f} s per loop")
print(f"Numpy multiplication: {numpy_time:.2f} s per loop")

Pure Python multiplication: 0.07 s per loop
Numpy multiplication: 0.11 s per loop


In [34]:
#q3
from timeit import timeit
def dot_python(Z1, Z2):
  return sum(z1 * z2 for z1, z2 in zip(Z1, Z2))
def dot_numpy(Z1, Z2):
  return np.dot(Z1, Z2)
Z1 = random.sample(range(1000000), 10000)
Z2 = random.sample(range(1000000), 10000)
python_time = timeit("dot_python(Z1,Z2)", globals=globals(), number=100)
numpy_time = timeit("dot_numpy(Z1,Z2)", globals=globals(), number=100)
print(f"Pure Python dot product: {python_time:.2f} s per loop")
print(f"Numpy dot product: {numpy_time:.2f} s per loop")

Pure Python dot product: 0.13 s per loop
Numpy dot product: 0.16 s per loop


In [33]:
#q4
from timeit import timeit
matrix1 = np.random.random((1000, 1000))
matrix2 = np.random.random((1000, 1000))
list1 = matrix1.tolist()
list2 = matrix2.tolist()
def matrix_python(list1, list2):
  list2_T = list(zip(*list2))
  return [[sum(a*b for a,b in zip(list1_row,list2_col)) for list2_col in list2_T] for list1_row in list1]
def matrix_numpy(matrix1, matrix2):
  return np.matmul(matrix1, matrix2)
#Z1 = random.sample(range(1000000), 10000)
#Z2 = random.sample(range(1000000), 10000)
python_time = timeit("matrix_python(list1,list2)", globals=globals(), number=1)
numpy_time = timeit("matrix_numpy(matrix1,matrix2)", globals=globals(), number=1)
print(f"Pure Python matrix multiplication: {python_time:.2f} s per loop")
print(f"Numpy matrix multiplication: {numpy_time:.2f} s per loop")

Pure Python matrix multiplication: 123.50 s per loop
Numpy matrix multiplication: 0.05 s per loop
